### ISSUE TITLE
Can't get flatstrap-rails to work

### ISSUE THREAD

**Issue by prashaantt** [fivetooldev/flatstrap-rails#1]
This is just the gem I was looking for, thanks!

I'm a Rails newbie, so it could be me, but I wasn't able to get flatstrap working using the instructions in your README.

In particular, `twitter-bootstrap-rails` doesn't seem to be updating application.css with the

```
/*
*= require bootstrap_and_overrides
*/
```

for static assets, so I don't know how else to replace the default bootstrap.css with flatstrap's. Did I miss something? Can you please fill in the missing steps for rank newbies?

**Comment by geoffharcourt** [comment]
Hi @prashaantt, did you run the twitter-bootstrap-rails static generator:
        rails generate bootstrap:install static

You need to run that command to install twitter-bootstrap-rails default assets before modifying the files for flatstrap.

**Comment by prashaantt** [comment]
Yes, I used the static generator. I'm getting this exception:

```
flatstrap/config/application.rb:13:in `<module:Flatstrap>': uninitialized constant Flatstrap::Rails::Application (NameError)
```

**Comment by geoffharcourt** [comment]
Can you paste in the output of `bundle list`?
