### ISSUE TITLE
couldn't find file 'flatstrap/bootstrap'

### ISSUE THREAD

**Issue by mkaravaev** [fivetooldev/flatstrap-rails#2]
Can't make Flatrap to work. I followed your instruction but rails said : "couldn't find file 'flatstrap/bootstrap'" Where am I gone wrong?

**Comment by geoffharcourt** [comment]
Hi @mkaravaev, could you paste the contents of your Gemfile.lock into a Gist and then link to it here? I want to see if there's a specific version of `twitter-bootstrap-rails` that might be responsible for the path problems.

**Comment by mkaravaev** [comment]
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (3.2.13)
      actionpack (= 3.2.13)
      mail (~> 2.5.3)
    actionpack (3.2.13)
      activemodel (= 3.2.13)
      activesupport (= 3.2.13)
      builder (~> 3.0.0)
      erubis (~> 2.7.0)
      journey (~> 1.0.4)
      rack (~> 1.4.5)
      rack-cache (~> 1.2)
      rack-test (~> 0.6.1)
      sprockets (~> 2.2.1)
    activemodel (3.2.13)
      activesupport (= 3.2.13)
      builder (~> 3.0.0)
    activerecord (3.2.13)
      activemodel (= 3.2.13)
      activesupport (= 3.2.13)
      arel (~> 3.0.2)
      tzinfo (~> 0.3.29)
    activeresource (3.2.13)
      activemodel (= 3.2.13)
      activesupport (= 3.2.13)
    activesupport (3.2.13)
      i18n (= 0.6.1)
      multi_json (~> 1.0)
    arel (3.0.2)
    bootstrap-sass (2.2.2.0)
      sass (~> 3.2)
    builder (3.0.4)
    chunky_png (1.2.8)
    coffee-rails (3.2.2)
      coffee-script (>= 2.2.0)
      railties (~> 3.2.0)
    coffee-script (2.2.0)
      coffee-script-source
      execjs
    coffee-script-source (1.6.3)
    compass (0.12.2)
      chunky_png (~> 1.2)
      fssm (>= 0.2.7)
      sass (~> 3.1)
    erubis (2.7.0)
    execjs (1.4.0)
      multi_json (~> 1.0)
    flatstrap-rails (0.3.0.2)
      twitter-bootstrap-rails (~> 2.2.6)
    flatstrap-sass (2.3.1.0)
      font-awesome-rails (~> 3.0.2.0)
      sass (~> 3.2)
    font-awesome-rails (3.0.2.0)
      railties (>= 3.1)
    fssm (0.2.10)
    hike (1.2.3)
    i18n (0.6.1)
    journey (1.0.4)
    jquery-rails (3.0.4)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    json (1.8.0)
    mail (2.5.4)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    mime-types (1.23)
    multi_json (1.7.7)
    pg (0.15.1)
    polyglot (0.3.3)
    rack (1.4.5)
    rack-cache (1.2)
      rack (>= 0.4)
    rack-ssl (1.3.3)
      rack
    rack-test (0.6.2)
      rack (>= 1.0)
    rails (3.2.13)
      actionmailer (= 3.2.13)
      actionpack (= 3.2.13)
      activerecord (= 3.2.13)
      activeresource (= 3.2.13)
      activesupport (= 3.2.13)
      bundler (~> 1.0)
      railties (= 3.2.13)
    railties (3.2.13)
      actionpack (= 3.2.13)
      activesupport (= 3.2.13)
      rack-ssl (~> 1.3.2)
      rake (>= 0.8.7)
      rdoc (~> 3.4)
      thor (>= 0.14.6, < 2.0)
    rake (10.1.0)
    rdoc (3.12.2)
      json (~> 1.4)
    sass (3.2.9)
    sass-rails (3.2.6)
      railties (~> 3.2.0)
      sass (>= 3.1.10)
      tilt (~> 1.3)
    simple_form (2.1.0)
      actionpack (~> 3.0)
      activemodel (~> 3.0)
    sprockets (2.2.2)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sqlite3 (1.3.7)
    thor (0.18.1)
    tilt (1.4.1)
    treetop (1.4.14)
      polyglot
      polyglot (>= 0.3.1)
    twitter-bootstrap-rails (2.2.7)
      actionpack (>= 3.1)
      execjs
      rails (>= 3.1)
      railties (>= 3.1)
    tzinfo (0.3.37)
    uglifier (2.1.2)
      execjs (>= 0.3.0)
      multi_json (~> 1.0, >= 1.0.2)

PLATFORMS
  ruby

DEPENDENCIES
  bootstrap-sass (~> 2.2.2.0)
  coffee-rails (~> 3.2.1)
  compass
  flatstrap-rails
  flatstrap-sass (~> 2.3.1.0)
  jquery-rails
  pg
  rails (= 3.2.13)
  sass-rails (~> 3.2)
  simple_form
  sqlite3
  twitter-bootstrap-rails
  uglifier (>= 1.0.3)

**Comment by geoffharcourt** [comment]
@mkaravaev, thanks for pasting that file. Could you also paste your Gemfile and application.css or application.css.scss? I'm still having trouble recreating your problem with a Rails 3.2 application.
